name: mini_projet_debut
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
#Aladydt;ukrymlkj
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_carousel_widget: ^3.1.0 #Pour appbar le slieder
  date_field: ^6.0.0 #Pour le dateTime
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - Assets/
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

